---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: log4shell-vulnerable-app
  name: log4shell-vulnerable-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log4shell-vulnerable-app
  template:
    metadata:
      labels:
        app: log4shell-vulnerable-app
    spec:
      containers:
      - image: amtoya/log4shell-vulnerable-app:latest
        imagePullPolicy: Always
        name: log4shell-vulnerable-app
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /usr/local/tomcat/temp
            name: tomcat-temp
          - mountPath: /usr/local/tomcat/work
            name: tomcat-work
          - mountPath: /usr/local/tomcat/logs
            name: tomcat-logs
      restartPolicy: Always
      volumes:
        - name: tomcat-temp
          emptyDir: {}
        - name: tomcat-work
          emptyDir: {}
        - name: tomcat-logs
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: log4shell-vulnerable-app
  name: log4shell-vulnerable-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: log4shell-vulnerable-app
